# Server
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:8080/mdm_db
spring.datasource.username=mdm_user
spring.datasource.password=mdm_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.mdm=DEBUG
logging.level.org.springframework.security=INFO
