spring.datasource.url=jdbc:postgresql://localhost:5432/mdm_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
logging.level.com.mdm=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.security.enabled=false